
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Category: /category
  Archives: /archives
  About: /about

# stylesheets loaded in the <head>
stylesheets:
- /css/reset.css
- /css/common.css
- /css/tab.css
- /css/sp.css
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/cuna.js
